In [1]:
import numpy as np
import pandas as pd

df_obj =pd.DataFrame({'data1':['a'] * 4 + ['b'] * 4,'data2':np.random.randint(0,4,8)})
print(df_obj)

  data1  data2
0     a      0
1     a      2
2     a      2
3     a      1
4     b      3
5     b      1
6     b      1
7     b      2

In [3]:
print(df_obj.duplicated())  # 找到重复的值

0    False
1    False
2     True
3    False
4    False
5    False
6     True
7    False
dtype: bool

In [4]:
df_obj[~df_obj.duplicated()]  #取出不重复行

  data1  data2
0     a      0
1     a      2
3     a      1
4     b      3
5     b      1
7     b      2

In [5]:
#按照某一列去重
print(df_obj.duplicated('data2'))

0    False
1    False
2     True
3    False
4    False
5     True
6     True
7     True
dtype: bool

In [6]:
df_obj1 = pd.DataFrame({'data1' :[np.nan] * 4,
                       'data2' :list('1235')})
df_obj1

   data1 data2
0    NaN     1
1    NaN     2
2    NaN     3
3    NaN     5

In [7]:
df_obj1.duplicated('data1') #nan值会被认为与nan值是重复的

0    False
1     True
2     True
3     True
dtype: bool

In [8]:
print(df_obj.drop_duplicates())  #删除重复行，是返回一个新的df，想要覆盖原有的，需要加inplce = True

  data1  data2
0     a      0
1     a      2
3     a      1
4     b      3
5     b      1
7     b      2

In [9]:
#map与applymap一样，但是map只能用于series，applymap只能用于df
ser_obj = pd.Series(np.random.randint(0,10,10))  #series 用map
print(ser_obj)

print(ser_obj.map(lambda x : x ** 2))

0    9
1    6
2    9
3    4
4    6
5    8
6    3
7    3
8    4
9    6
dtype: int32
0    81
1    36
2    81
3    16
4    36
5    64
6     9
7     9
8    16
9    36
dtype: int64

In [10]:
#异常值手动替换
ser_obj=pd.Series(np.arange(10),index=range(3,13))
# 单个值替换单个值
print(ser_obj.replace(1, -100))
print('-' * 20)
# 多个值替换一个值
print(ser_obj.replace(range(6,9), -100))
print('-' * 20)
# 多个值替换多个值
print(ser_obj.replace([4, 7], [-100, -200]))

3       0
4    -100
5       2
6       3
7       4
8       5
9       6
10      7
11      8
12      9
dtype: int32
--------------------
3       0
4       1
5       2
6       3
7       4
8       5
9    -100
10   -100
11   -100
12      9
dtype: int32
--------------------
3       0
4       1
5       2
6       3
7    -100
8       5
9       6
10   -200
11      8
12      9
dtype: int32